#!/usr/bin/env bash

# stabilize videos in a directory
stabilize() {
    for a in *.mp4; do
        ffmpeg -i "$a" -vf vidstabdetect -f null -
        ffmpeg -i "$a" -vf vidstabtransform "stabilized$a"
        rm transforms.trf "$a"
    done
}

# merge a photo with a song
tothumbnail() {
    ffmpeg -loop 1 -i thumbnail.png -i song.wav -c:v libx265 -c:a aac -b:a 256k -pix_fmt yuv420p -shortest out.mp4
}

# blur background of vertical videos in current directory
blurbackground() {
    for a in *.mp4; do
        ffmpeg -i "$a" -filter_complex "[0:v]scale=ih*16/9:-1,boxblur=luma_radius=min(h\,w)/20:luma_power=1:chroma_radius=min(cw\,ch)/20:chroma_power=1[bg];[bg][0:v]overlay=(W-w)/2:(H-h)/2,crop=h=iw*9/16" "blurred$a"
        rm "$a"
    done
}

# Loop videos in directory for a specific time
loopvideo() {
    for a in *.mp4; do
        ffmpeg -stream_loop -1 -i "$a" -c:v libx265 -tag:v hvc1 -movflags faststart -vf scale=1268:-2 -t "$1" "looped$a"
        rm -r "$a"
    done
}
