#!/usr/bin/env bash
set -eo pipefail

# ---------------
# Credit for this script goes to https://github.com/killjoy1221
# I modified it a little to make it not use strings
# ---------------

# TODO:
#  * pip????
#  * add cli?

NO_FORMAT="\033[0m"
C_TEAL="\033[38;5;6m"

function run() {
    local prog=$1
    if [[ $prog == sudo ]]; then
        prog=$2
    fi
    if [[ -n "$(command -v "$prog")" ]]; then
        echo -e "${C_TEAL}\$${NO_FORMAT} $*"
        "$@"
    fi
}

function main() {
    run sudo dnf upgrade --refresh
    run sudo dnf autoremove
    run update-luarocks
    run rustup update
    run cargo-install-update install-update --all
    run pnpm update -gL
    run pipx upgrade-all
    run pip cache purge
}

main
