#!/usr/bin/env bash
set -eo pipefail

rockarray=()
mapfile -t rockarray < <(luarocks list --outdated --porcelain | cut -f1)
if [[ ${#rockarray[@]} -ne 0 ]]; then
    for rock in "${rockarray[@]}"; do
        echo -e "Updating $rock..."
        sh -c "luarocks install --local $rock"
    done
    echo -e "All done!"
else
    echo -e "All rocks up to date!"
fi
