#!/usr/bin/env bash
set -eo pipefail

# ---------------
# Credit for this script goes to https://github.com/killjoy1221
# I simply added a main function
# ---------------

# TODO:
#  * pip
#  * add cli?

NO_FORMAT="\033[0m"
C_TEAL="\033[38;5;6m"

update-script() {
    local cmdline="$1"
    local prog=${cmdline%% *}
    local progargs=${cmdline#* }
    if [[ $prog == sudo ]]; then
        prog=${progargs%% *}
    fi
    if [[ -n "$(command -v "$prog")" ]]; then
        echo -e "${C_TEAL}\$${NO_FORMAT} ${cmdline[*]}"
        sh -c "${cmdline[@]}"
    fi
}

declare -a updates=(
    "sudo dnf upgrade --refresh"
    "sudo dnf autoremove"
    "update-luarocks"
    "gem update"
    "gem cleanup"
    "rustup update"
    "cargo-install-update install-update --all"
    "pnpm update -gL"
    "rye self update"
    "pipx upgrade-all"
    "pip cache purge"
)

main() {
    for cmd in "${updates[@]}"; do
        update-script "$cmd"
    done
}

main
