cache: null
def-ghc-conf-options: null
downloader: Curl
gpg-setting: null
guess-version: null
keep-dirs: null
key-bindings: null
meta-cache: null
meta-mode: null
mirrors: null
no-network: null
no-verify: null
pager: null
platform-override: null
url-source:
- GHCupURL
verbose: null
